<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="3" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2020-06-26T01:22:26 CDT" name="All Test Suite" finished-at="2020-06-26T01:22:52 CDT" duration-ms="25828">
    <groups>
    </groups>
    <test started-at="2020-06-26T01:22:26 CDT" name="/Users/ridvangunduz/IdeaProjects/EndToEndProject" finished-at="2020-06-26T01:22:52 CDT" duration-ms="25828">
      <class name="Framework.TestToFail">
        <test-method signature="failThisTest()[pri:0, instance:Framework.TestToFail@54eb2b70]" started-at="2020-06-26T01:22:26 CDT" name="failThisTest" finished-at="2020-06-26T01:22:30 CDT" duration-ms="3227" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertTrue(Assert.java:43)
at org.testng.Assert.assertTrue(Assert.java:53)
at Framework.TestToFail.failThisTest(TestToFail.java:18)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1507)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:284)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:119)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:562)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- failThisTest -->
      </class> <!-- Framework.TestToFail -->
      <class name="Framework.Test2">
        <test-method signature="getRandomPersons()[pri:0, instance:Framework.Test2@74a6f9c1]" started-at="2020-06-26T01:22:26 CDT" name="getRandomPersons" finished-at="2020-06-26T01:22:26 CDT" duration-ms="304" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getRandomPersons -->
      </class> <!-- Framework.Test2 -->
      <class name="HomePage.HomePage">
        <test-method signature="homePageLogin(java.lang.String, java.lang.String)[pri:0, instance:HomePage.HomePage@45a37759]" started-at="2020-06-26T01:22:30 CDT" name="homePageLogin" data-provider="getData" finished-at="2020-06-26T01:22:41 CDT" duration-ms="11392" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chas.bahringer]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[22851151]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- homePageLogin -->
        <test-method signature="homePageLogin(java.lang.String, java.lang.String)[pri:0, instance:HomePage.HomePage@45a37759]" started-at="2020-06-26T01:22:41 CDT" name="homePageLogin" data-provider="getData" finished-at="2020-06-26T01:22:52 CDT" duration-ms="10763" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[testemail@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[test12345]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- homePageLogin -->
      </class> <!-- HomePage.HomePage -->
    </test> <!-- /Users/ridvangunduz/IdeaProjects/EndToEndProject -->
  </suite> <!-- All Test Suite -->
</testng-results>
